### ISSUE TITLE
monorepo vs multirepo

### ISSUE THREAD

**Issue by joaomilho** [klarna/ui-react-components#49]
#### 2 repos / 2 packages

- Requires `ls`ing of ui-css on ui-react and of ui-react into a project to test;
- 2 different build scripts;
- Publish twice;
- Keeps versions independent but peered;

#### 1 repo / 2 packages
- ui-react still needs to ref css files from the lib (@klarna/ui-css-components/...), therefore it doesn't help much with ls'ing issues;
- Allows rethinking showcase;
- Could have only 1 build script;
- Can keep versions independent or synced (lerna.js)

#### 1 repo / 1 package
 - Requires install of react components when only css changes & overall download is higher for css-only users (not very relevant);
 - Single publish;
 - Should have only 1 build script;
 - Keeps only 1 version, therefore in sync;
 - Allows rethinking showcase;

**Comment by JoakimLofgren** [comment]
**2 repos / 2 packages**
Having two showrooms is also a pretty annoying con :(
And when adding a new css class, you need to update both repos and update both showrooms.

**1 repo / 2 packages**
You don't need lerna for 1 repo 2 packages, just look at react:
https://github.com/facebook/react/blob/master/package.json
https://github.com/facebook/react/blob/master/packages/react-dom/package.json

Although I think a release to just css would need a release to js as well.
I think having a synced version would be nice.

**1 repo / 1 package**
You could still create a compiled css file for the css only users.
Which you probably would want for a static page generator project.


@joaomilho I would vote for 1 / 2. But I could go with 1 / 1 as well.

**Comment by xaviervia** [comment]
**2 repos / 2 packages**

The showroom is a big con in this one. Since we will have a single showroom when we implement @hannah-ahl 's design, we would need to create another repo just to host the showroom or something like that. Also, PR'ing and upgrading can get pretty bureaucratic and makes experimentation harder.

**1 repo / 2 packages**

I think this is a fair approach, but I don't know how CSS-only consumers are using the components. They might be using bower, in which case **1 repo / 2 packages** will mean **1 repo / 1 package** for them.

**1 repo / 1 package**

I think the overhead for consumers of the CSS components would be a little to big. If we were to go only React this would be the preferred approach however.

I vote for 1 / 2, but can live with any.

**Comment by matthiasfeist** [comment]
I vote for 1/2 or 1/1.
Although I think 1/1 is nicer :)

**Comment by ChristerGustavsson** [comment]
I'll vote for 1/2. I'm guessing that will make it easier for people to consume only the css if they wish. It might be a moot point because I do not know how many actually need that.

I'm fine with 1/1 as well because that would probably make maintenance easier.

**Comment by joaomilho** [comment]
I vote for 1/1 since I think the maintenance advantages trump any difficulty with css-only consumption (which is perfectly solvable, it might just give _some_ work if we decide to ditch gulp and go webpack all the way).

**Comment by joaomilho** [comment]
I guess we need the people who are for 2 repos to weight in.

**Comment by Nevon** [comment]
I'm generally fairly allergic to the monorepo structure, but I'm not sure the term is even applicable here. From the discussion, it seems that the `ui-react-components` and `ui-css-components` are actually just two artefacts of the same project. The fact that they are in two different repos is purely because of technical reasons, not for organizational purposes.

That said, I think there's value in having two packages, as having just a single package will cause frictions for teams who would like to use the ui-toolkit, but who don't use React.

**Comment by joaomilho** [comment]
Let's get more concrete. I think the 2 real use cases we have are a) using react on an import basis b) using css using the whole bundle. I suppose the usage of css through imports is marginal. Therefore, we could end up with this API for consumption of react components:

```js
import Field from '@klarna/ui/components/Field'
// or moving it to the run when building
import Field from '@klarna/ui/Field'
```

and internally we would include the css more or less like this, assuming we can move the current `field.scss` to the same folder `Field` is sitting:

```js
import styles from './styles.scss'
```

Here's an outline of file structure:

<pre>
components/
  Field/
    index.jsx // the current components/Field.jsx on ui-react
    styles.scss // the current src/components/field.scss on ui-css
</pre>

///

Finally, assuming css consumers need the bundled css, we could go all the way and have the versions published directly to S3 (mirrored by Akamai), as in: https://x.klarnacdn.net/ui.1.2.3.css

Actually this leads us to discuss how to chunk the react build itself leveraging the CDN, so @JoakimLofgren will write an issue about this specific topic outlining a comprehensive solution.

**Comment by xaviervia** [comment]
I think what you say @Nevon about it being really just a single project that got split due to technical reasons makes a lot of sense. It makes the argument of having a single package more compelling. I know for a fact that there are consumers using scss via direct imports, but that is not really an issue with the proposal that @joaomilho is putting forward. I think we can take the opportunity to simplify paths _a lot_, since right now they are kind of cumbersome.

I'm leaning for 1/1 now, as long as we make sure that 1 still allows for direct consumption of SCSS and we publish the built CSS either in the NPM or in a CDN or both.

**Comment by joaomilho** [comment]
So after this whole discussion I assume the decision is to have 1 repo and 1 package (`@klarna/ui`), provided people can still consume the css from it, either on a module basis or from a main (or ideally from a CDN).
